### PR TITLE
Add 2 new images (gh-pages branch)

### PR DESCRIPTION
**Pull request by leeceeksdee**

### CODE REVIEW

**Review by cheesits456 — CHANGES_REQUESTED** [review]
Same thing I said in https://github.com/cheesits456/ReactionPics/pull/1#pullrequestreview-486142205, plus a couple other small things:

- make sure you set the `og:image:type` meta tag's `content` attribute to `image/gif` for gifs
- update the `og:image:alt` meta tag's `content` attribute to reflect the new file name
- make sure you've edited the redirect link in the `<script>` tag

**Comment by leeceeksdee** [comment]
done

**Review by cheesits456 — CHANGES_REQUESTED** [review]
almost perfect, just one small thing you missed - in `./juice/index.html`, make sure the redirect link in the `<script>` tag has a `.gif` file extension, not `.jpg`

**Review by cheesits456 — APPROVED** [review]
just noticed i can change the file even though i don't own the fork

**Pull request merged**
